import type { Metadata } from "next";
import { Poppins, Playfair_Display } from "next/font/google";
import localFont  from "next/font/local";
import Navbar from "@/components/Navbar";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

const thunder = localFont({
  src: [
    {
      path: "../public/fonts/Thunder-BoldHC.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/Thunder-BlackHC.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-thunder",
});

export const metadata: Metadata = {
  title: "Julyan Putra | Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${playfair.variable} ${thunder.variable} antialiased w-full overflow-x-hidden bg-black text-stone-200`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
