import type { Metadata } from "next";
import { Poppins, Playfair_Display, Rye } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";


const rye = Rye({
  variable: '--font-rye',
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
});


const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "600", "700"], 
});

export const metadata: Metadata = {
  title: "Julyan Putra | Portofolio",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en">
  <body
    className={`${poppins.variable} ${playfair.variable} antialiased max-w-screen bg-stone-200 text-stone-200`}
  >
    <Navbar/>
    {children}
    
  </body>
</html>

  );
}
